version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:9-jdk-browsers

    steps:

      - checkout

      - run: echo 'export TERM=xterm' >> $BASH_ENV
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - restore_cache:
          key: circleci-java-{{ checksum "build.gradle" }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-java-{{ checksum "build.gradle" }}

      - run: ./gradlew test
