version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:9-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: circleci-java-{{ checksum "build.gradle" }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-java-{{ checksum "build.gradle" }}

      - run: ./gradlew test
